### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by kwalker99** [aaronaanderson/Terrain#1]
Hi Aaron

As discussed, please can you compile a Linux VST2 and VST3 versions.

Happy to test etc

Kind regards

Kevin

**Comment by aaronaanderson** [comment]
Hi Kevin, 

Here is a link to the .deb package: https://drive.google.com/file/d/1W272p69FjoPz3YE3wiF5Uz5CDiKp6br-/view?usp=sharing
I've updated the youtube description with this link. I verified it on my machine but would feel more confident if you verified it on your machine as well. It's VST3 only since Steinberg deprecated the VST2 SDK.

Thank you!

Aaron

**Comment by kwalker99** [comment]
Working perfectly :-)

[image: image.png]

**Comment by aaronaanderson** [comment]
Thank you for verifying!
