### ISSUE TITLE
Pitch bend - MPE - CLAP

### ISSUE THREAD

**Issue by TjShredder** [aaronaanderson/Terrain#4]
I would love to see at least a pitch bend option, or even better MPE. This synth with its unique oscillator is crying for per voice modulation. Maybe even a CLAP version, which is made for per voice modulation... 
VST3 Note expressions could work as well to play it expressively with my Linnstrument...

**Comment by aaronaanderson** [comment]
Hi @TjShredder, 

* I've already implemented pitch bend in the develop branch; it will be in the next release (1.0.3) in the next week or two.
* Clap support will be unlikely I'm afraid. This plugin uses the JUCE audio framework in order to build for multiple OSs and multiple formats; the CLAP format is not natively supported in this framework yet. I did find a third-party implementation however. I do not trust third-party code nearly as much as native JUCE code, but apparently the SURGE synth is using this so that gives me enough confidence to give it a look. However, it's not a high priority since VST3/AU/AAX support every feature that I want to take advantage of (see below)
* MPE support is on the roadmap (by version 1.2.0) - this should cover the capabilities of your Linnstrument. First on my roadmap is microtonality support (by version 1.1.0) via MTS-ESP. Adding MPE support is a bit of a major code change because I will have to add additional interface, will have to branch the internal mechanics of the synthesis engine, and will have to make all parameters assignable to the various dimensions provided by MPE. In the end I plan to have a standard 12-tone mode, a microtonal mode, and an MPE mode.

Thank you for your input - it's helpful to know what features users want! Since the roadmap has been updated, I'm going to close the issue with this response.

Best, 
Aaron

**Comment by RustoMCSpit** [comment]
> 
Clap support will be unlikely I'm afraid. This plugin uses the JUCE audio framework in order to build for multiple OSs and multiple formats; the CLAP format is not natively supported in this framework yet. I did find a third-party implementation however. I do not trust third-party code nearly as much as native JUCE code, but apparently the SURGE synth is using this so that gives me enough confidence to give it a look. However, it's not a high priority since VST3/AU/AAX support every feature that I want to take advantage of (see below)

more than just using it, they made it

https://github.com/free-audio/clap-juce-extensions

it's made by baconpaul whos very involved in surge, clap, and juce. you should try it. juce support for clap seems years away and id love to add this to my list https://github.com/RustoMCSpit/awesome-linux-clap-list

**Comment by aaronaanderson** [comment]
@RustoMCSpit Version 1.1.0 is out! This includes CLAP support as requested.

**Comment by RustoMCSpit** [comment]
do you have to put in a .deb file? it'd be a lot easier to just have a .clap i can drag and drop then being forced to install vst3 and lv2 among other dependencies

**Comment by RustoMCSpit** [comment]
also thank you!

**Comment by aaronaanderson** [comment]
I just updated the Linux .tar.gz to include both the .deb and the individual plugin files for those who wish to manually install: https://github.com/aaronaanderson/Terrain/releases/tag/1.1.0
I'll release it like this on Linux from now on.

**Comment by RustoMCSpit** [comment]
thank you aaron
